Revert "Try getting rid of explicit meta.platforms"
This reverts commit 676b66bd428fe68c719145009dbf015b4afd7ef1.

Without the explicit platforms, I got the following error:

```
error: Package ‘emacs-with-packages-25.1’ in /nix/store/rh1mrwq3z8iym1j3n4ryav63almylndc-emacs-ci/emacs-ci/emacs.nix:67 is not supported on ‘x86_64-linux’, refusing to evaluate.

a) For `nixos-rebuild` you can set
  { nixpkgs.config.allowUnsupportedSystem = true; }
in configuration.nix to override this.

b) For `nix-env`, `nix-build`, `nix-shell` or any other Nix command you can add
  { allowUnsupportedSystem = true; }
to ~/.config/nixpkgs/config.nix.
```